application:
  subdomain: einksync
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://einksync:5000/
services:
  einksync:
    #  xiaokun566/einksync:latest
    # upstream: docker.io/xiaokun566/einksync:latest@sha256:ecfd8d9161a021856f02d36040dc3c80b7d4764e66e455433288a7619f5ec4b0
    image: docker.1ms.run/xiaokun566/einksync:latest@sha256:ecfd8d9161a021856f02d36040dc3c80b7d4764e66e455433288a7619f5ec4b0
    binds:
      - /lzcapp/var/data:/app/data
      - /lzcapp/var/downloads:/app/downloads
      - /lzcapp/var/library:/app/library
